global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-apps'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway-service:8080', 'click-analytics:8081']