spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: analytics-group # Уникальный для этого сервиса
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  data:
    cassandra:
      contact-points:
        - cassandra
      keyspace-name: clicker
      local-datacenter: datacenter1
      connection:
        connect-timeout: 30s
        init-query-timeout: 30s
      request:
        timeout: 20s
        consistency: local_one
      pool:
        idle-timeout: 10s
        heartbeat-interval: 30s
  cassandra:
    keyspace-name: clicker
    schema-action: CREATE_IF_NOT_EXISTS

auto:
  create:
    topics:
      enable: false
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    prometheus:
      enabled: true